apiVersion: v1
kind: ConfigMap
metadata:
  name: welcome-client
  namespace: default
data:
  HOSTNAME: "0.0.0.0"
  NODE_ENV: production

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcomeclient
  template:
    metadata:
      labels:
        app: welcomeclient
    spec:
      containers:
        - name: welcomeclient
          image: lucassandin/welcome-client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: welcome-client
                  key: HOSTNAME
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: welcome-client
                  key: NODE_ENV
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: welcomeclient
#   namespace: default
#   labels:
#     app: welcomeclient
# spec:
#   ports:
#     - name: http
#       port: 3001
#       protocol: TCP
#       targetPort: 3000
#   selector:
#     app: welcomeclient
#   type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: welcomeclientnodeport
spec:
  selector:
    app: welcomeclient
  ports:
    - port: 3001
      targetPort: 3000
      nodePort: 30001
  type: NodePort
