apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}-service
  namespace: {{ .Values.application.namespace }}
spec:
  selector:
    app: {{ .Values.application.app }}
  ports:
    - port: {{ .Values.application.service.port }}
      targetPort: {{ .Values.application.service.targetPort }}
  type: {{ .Values.application.service.type }}
