apiVersion: v1
entries:
  welcome-client:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-04-30T11:59:26.891816279Z"
    description: A Helm chart for Kubernetes
    digest: ce28622d6a2adedddac92526d0920e86593c5765f3c3ac56ae5e5a139edc6970
    name: welcome-client
    type: application
    urls:
    - https://lucassandin.github.io/client.welcome.github.io/charts/welcome-client-v18.tgz/welcome-client-v18.tgz
    version: v18
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-04-30T11:59:26.891511329Z"
    description: A Helm chart for Kubernetes
    digest: c2c1e54d62d3a27b3d9c1c06e9fcd416c104758a693b44f27b8ede4f44d8bb19
    name: welcome-client
    type: application
    urls:
    - https://lucassandin.github.io/client.welcome.github.io/charts/welcome-client-v18.tgz/welcome-client-v16.tgz
    version: v16
generated: "2024-04-30T11:59:26.891110691Z"
