application:
  name: welcome-client
  namespace: frontend
  app: welcome-client
  version: "v1.0.10"
  configMap:
    data:
      HOSTNAME: "0.0.0.0"
      NODE_ENV: production
      NEXT_PUBLIC_API: http://api.34.67.168.100.nip.io/api/v1
  deployment: 
    containers:
      - name: welcome-client
        image: lucassandin/welcome-client:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        env:
          - name: HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: welcome-client-configmap
                key: HOSTNAME
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: welcome-client-configmap
                key: NODE_ENV
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
  ingress:
    ingressClassName: nginx
    rules:
      host: client.34.67.168.100.nip.io
      path: /
      pathType: Prefix
      port:
        number: 80
