name: CI-CD

on: 
  push: 
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.2
      
      - name: Docker login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v5.3.0
        with: 
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            lucassandin/welcome-client:${{github.run_number}}
            lucassandin/welcome-client:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
  
    steps:
      - uses: actions/checkout@v4.1.2
      
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2.1.0
        with:
          cluster_name: cluster-backstage
          location: us-central1-a
            

      #- name: Google Kubernetes Engine deployment
        #uses: piotr-krusinski/action-google-kubernetes-engine-deployment@v1.0
        #with:
          #google_project_id: welcome-api-419616 #${{secrets.GCLOUD_PROJECT_ID}}
          #google_kubernetes_cluster_name: cluster-backstage #${{secrets.GCLOUD_CLUSTER_NAME}}
          #google_kubernetes_cluster_zone: us-central1-a #${{secrets.GCLOUD_CLUSTER_ZONE}}
          #service_account_key: ${{secrets.GCLOUD_SERVICE_ACCOUNT_KEY}}
          #application_name: ${{secrets.GCLOUD_APPLICATION_NAME}}
          #container_name: ${{secrets.GCLOUD_CONTAINER_NAME}}
          #image_repo_url: lucassandin/welcome-client:${{github.run_number}}
          #image_name: lucassandin/welcome-client:${{github.run_number}}
          #image_tag: lucassandin/welcome-client:${{github.run_number}}
          #namespace: ${{secrets.GCLOUD_CLUSTER_NAMESPACE}}
          

      #- name: Deploy to Kubernetes cluster
      #  uses: Azure/k8s-deploy@v4.9
      #  with:
      #    images: lucassandin/welcome-client:${{github.run_number}}
      #    manifests: ./k8s/deployment.yaml
            
