name: CI-CD

on: 
  push: 
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.2
      
      - name: Docker login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      
#      - name: Construção da imagem Docker
#        uses: docker/build-push-action@v5.3.0
#        with: 
#          context: ./
#          file: ./Dockerfile
#          push: true
#          tags: |
#            lucassandin/welcome-client:${{github.run_number}}
#            lucassandin/welcome-client:latest

#  CD:
#    runs-on: ubuntu-latest
#    needs: [CI]
#  
#    steps:
#      - uses: actions/checkout@v4.1.2
#      
#      - name: Kubernetes Set Context
#        uses: Azure/k8s-set-context@v3.0
#        with:
#          method: kubeconfig
#          kubeconfig: ${{secrets.K8S_CONFIG}}
# 
#      - name: Deploy to Kubernetes cluster
#        uses: Azure/k8s-deploy@v4.9
#        with:
#          images: lucassandin/welcome-client:${{github.run_number}}
#          manifests: ./k8s/deployment.yaml
          
  CDD:
    runs-on: ubuntu-latest
    needs: [CI]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}

      - uses: simenandre/setup-gke-gcloud-auth-plugin@v1

      - name: Google github actions/get credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{secrets.GOOGLE_CLUSTER_NAME}}
          location: ${{secrets.GOOGLE_CLUSTER_ZONE}}

      # At this point you should be able to communicate with your cluster
      #- run: kubectl get pods

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.9
        with:
          images: lucassandin/welcome-client:${{github.run_number}}
          manifests: ./k8s/deployment.yaml
